### ISSUE TITLE
Localized date

### ISSUE THREAD

**Issue by vildibald** [durasj/octosign-website#4]
On the _Download_ page there is a release date. In SK version the date is in EN format, e.g. 06/01/2020
For Slovak users it may be confusing if the app has been released on June 1 or January 6.

![Screenshot from 2020-06-05 13-29-50](https://user-images.githubusercontent.com/8437487/83871760-f3df7c00-a730-11ea-8785-67c60b4f4e34.png)

**Comment by durasj** [comment]
Thank you for reporting this @vildibald! I've changed this so it's `YYYY-MM-DD` in English - so it's ISO catch-all as different English speaking nations have different date formats. And then in Slovak specifically it's in `DD.MM.YYYY`.
